version: '3.8'

# Development Docker Compose with hot reload
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: invoice-backend-dev
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=docker
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend:delegated
      - ./requirements.txt:/app/requirements.txt:ro
    networks:
      - invoice-network
    restart: unless-stopped
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    image: node:20-alpine
    container_name: invoice-frontend-dev
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://backend:8000
      - NODE_ENV=development
    env_file:
      - frontend-nextjs/.env.local
    volumes:
      - ./frontend-nextjs:/app:delegated
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - invoice-network
    restart: unless-stopped
    command: sh -c "npm install && npm run dev"

networks:
  invoice-network:
    driver: bridge

